#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-strato-bot-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the strato-bot Docker image
        run: |
          docker build . -t ghcr.io/finr0y/strato-bot:latest
          docker push ghcr.io/finr0y/strato-bot:latest